use_frameworks!

platform :ios, '8.0'

target 'MyTool_Example' do
  pod 'MyTool', :path => '../'
  pod 'MyHUD', :path => '../../MyHUD'
  target 'MyTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
